/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f8f9fa",
        "surface-container-high": "#e5e9eb",
        "on-primary": "#f5f9ff",
        "on-primary-fixed-variant": "#2a5975",
        "tertiary-fixed-dim": "#bbc1ef",
        "primary-fixed-dim": "#a1cfef",
        "secondary-container": "#d1e6f0",
        "surface-variant": "#dee3e6",
        "primary-dim": "#285874",
        "surface-bright": "#f8f9fa",
        "on-tertiary-container": "#3e456c",
        "secondary-fixed": "#d1e6f0",
        "tertiary-container": "#c9cffe",
        "on-primary-container": "#1e4f6b",
        "secondary": "#4f626b",
        "on-tertiary": "#faf8ff",
        "tertiary-fixed": "#c9cffe",
        "on-primary-fixed": "#003c57",
        "inverse-surface": "#0c0f10",
        "error-dim": "#67040d",
        "surface-dim": "#d5dbdd",
        "on-error": "#fff7f6",
        "primary": "#366480",
        "on-tertiary-fixed-variant": "#484e76",
        "on-background": "#2d3335",
        "on-secondary-fixed": "#2f424a",
        "outline": "#767c7e",
        "secondary-dim": "#43565f",
        "surface-container-highest": "#dee3e6",
        "surface": "#f8f9fa",
        "on-secondary-container": "#41545d",
        "tertiary": "#565d85",
        "error-container": "#fa746f",
        "on-error-container": "#6e0a12",
        "surface-container": "#ebeef0",
        "on-surface-variant": "#5a6062",
        "on-surface": "#2d3335",
        "secondary-fixed-dim": "#c3d8e2",
        "tertiary-dim": "#4a5178",
        "primary-container": "#afddfe",
        "on-secondary": "#f2faff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#9b9d9e",
        "outline-variant": "#adb3b5",
        "on-tertiary-fixed": "#2b3257",
        "inverse-primary": "#afddfe",
        "on-secondary-fixed-variant": "#4b5e67",
        "surface-container-low": "#f1f4f5",
        "primary-fixed": "#afddfe",
        "error": "#a83836",
        "surface-tint": "#366480"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
